- id: '1654370498791'
  alias: Unlock back door when garage opens
  description: ''
  trigger:
  - platform: device
    device_id: 1579eced18a15363a26d17f2cce51d0f
    domain: cover
    entity_id: cover.garage_door_opener
    type: opened
  condition: []
  action:
  - device_id: 4a0e2215f9effd5201d8df743cccde28
    domain: lock
    entity_id: lock.touchscreen_deadbolt
    type: unlock
  mode: single
- id: '1654919466319'
  alias: Front Door Scenes
  description: ''
  use_blueprint:
    path: fxlt/zen32-scene-controller-z-wave-js.yaml
    input:
      zooz_switch: 0ca9601b44374b3932e2e4d9f5627689
      scene_1: []
      scene_2:
      - if:
        - condition: sun
          before: sunset
        then:
        - type: turn_on
          device_id: 0ca9601b44374b3932e2e4d9f5627689
          entity_id: light.front_porch_cans
          domain: light
        else:
        - type: turn_off
          device_id: 0ca9601b44374b3932e2e4d9f5627689
          entity_id: light.front_porch_cans
          domain: light
- id: '1635120095657'
  alias: Night Lights On
  description: Turn on lights at night
  trigger:
  - platform: sun
    event: sunset
    offset: -00:45:00
  condition: []
  action:
  - type: turn_on
    device_id: 72098e3be641ae38ac321c0bdde7c382
    entity_id: switch.black_smart_plug
    domain: switch
  - type: turn_on
    device_id: 23b8b981edb56926ed5dbdd1eb0ae061
    entity_id: switch.white_outdoor_plug_1
    domain: switch
  - type: turn_on
    device_id: 845fd7213af79f347ac7b87f56611075
    entity_id: light.front_porch_sconces
    domain: light
  - type: turn_on
    device_id: d45fe2e810794abef59494d01cf9267c
    entity_id: light.entryway_light
    domain: light
  - type: turn_on
    device_id: 0ca9601b44374b3932e2e4d9f5627689
    entity_id: light.front_porch_cans
    domain: light
  - type: turn_on
    device_id: 346bb2426e72599e477a9da8d71b6cab
    entity_id: light.back_door_sconces
    domain: light
  mode: single
- id: '1637542497005'
  alias: Night Lights Off
  description: Turn outside lights off
  trigger:
  - platform: time
    at: '22:30:00'
  condition: []
  action:
  - type: turn_off
    device_id: 72098e3be641ae38ac321c0bdde7c382
    entity_id: switch.black_smart_plug
    domain: switch
  - type: turn_off
    device_id: 23b8b981edb56926ed5dbdd1eb0ae061
    entity_id: switch.white_outdoor_plug_1
    domain: switch
  - type: turn_off
    device_id: 346bb2426e72599e477a9da8d71b6cab
    entity_id: light.back_door_sconces
    domain: light
  - type: turn_off
    device_id: df9c9f05617a2fe7f6e093b36b239ca2
    entity_id: switch.back_porch_lights
    domain: switch
  - type: turn_off
    device_id: 845fd7213af79f347ac7b87f56611075
    entity_id: light.front_porch_sconces
    domain: light
  - type: turn_off
    device_id: 0ca9601b44374b3932e2e4d9f5627689
    entity_id: switch.front_porch_cans
    domain: switch
  mode: single
- id: '1655343909328'
  alias: Walk out of Home Theater
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.jamie_s22
    attribute: distance
    above: '8'
  condition: []
  action:
  - type: turn_off
    device_id: 2460edda7fbbeb7d702ba74eef896b34
    entity_id: light.home_theater_light
    domain: light
  mode: single
- id: '1655392965026'
  alias: Home Theater Light off when watching something
  description: ''
  trigger:
  - platform: device
    device_id: 1d52216c126d3b76c4854515564d14d0
    domain: media_player
    entity_id: media_player.home_theater_appletv
    type: playing
  condition: []
  action:
  - type: turn_off
    device_id: 2460edda7fbbeb7d702ba74eef896b34
    entity_id: light.home_theater_light
    domain: light
  mode: single
- id: '1655393092824'
  alias: Home Theater Light on when turning off TV
  description: ''
  trigger:
  - platform: device
    device_id: 4c107d4c06ee12191f9459046a1b25fd
    domain: media_player
    entity_id: media_player.denon_avr_x6400h
    type: turned_off
  condition: []
  action:
  - type: turn_on
    device_id: 2460edda7fbbeb7d702ba74eef896b34
    entity_id: light.home_theater_light
    domain: light
  mode: single
- id: '1655674408251'
  alias: Jamie Enters Office
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.jamie_s22
    to: office
    from: kitchen
  condition: []
  action:
  - device_id: eedfc70c639a2a6fcaad5b213e35458c
    domain: mobile_app
    type: notify
    message: You're in your office
  mode: single
- id: '1656290951933'
  alias: Walk into Office
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.jamie_s22
    attribute: distance
    below: '4'
  condition:
  - condition: state
    entity_id: sensor.jamie_s22
    attribute: friendly_name
    state: office
  action:
  - type: turn_on
    device_id: 03f2f866c2dbb37d416b4d6e4cb586dc
    entity_id: light.z_wave_plus_700_series_dimmer_switch
    domain: light
  mode: single
- id: '1656421371508'
  alias: Silas is awake
  description: ''
  trigger:
  - platform: device
    device_id: fb6f7dbf0df07e16b46ffbd74c5308a9
    domain: media_player
    entity_id: media_player.kitchen_display
    type: playing
    for:
      hours: 0
      minutes: 2
      seconds: 0
  condition:
  - condition: time
    before: 08:00:00
    after: 00:00:00
    weekday:
    - sat
    - sun
  action:
  - service: media_player.play_media
    target:
      entity_id: media_player.kitchen_hub
    data:
      media_content_id: media-source://tts/google_translate?message=Silas+is+awake
      media_content_type: provider
    metadata:
      title: Silas is awake
      thumbnail: https://brands.home-assistant.io/_/google_translate/logo.png
      media_class: app
      children_media_class:
      navigateIds:
      - {}
      - media_content_type: app
        media_content_id: media-source://tts
      - media_content_type: provider
        media_content_id: media-source://tts/google_translate?message=Silas+is+awake
  mode: single
- id: '1664589626944'
  alias: Turn server room light off after 5 minutes
  description: ''
  trigger:
  - platform: device
    type: turned_on
    device_id: b6d35644182fead040d39b098c0a42ee
    entity_id: light.server_room_light
    domain: light
    for:
      hours: 0
      minutes: 5
      seconds: 0
  condition: []
  action:
  - type: turn_off
    device_id: b6d35644182fead040d39b098c0a42ee
    entity_id: light.server_room_light
    domain: light
  mode: single
- id: '1664759246970'
  alias: 'Home theater light with TV off '
  description: ''
  trigger:
  - type: occupied
    platform: device
    device_id: cebaa2dd2b84e6d55753dc58fd6fda59
    entity_id: binary_sensor.nest_protect_home_theater_occupancy
    domain: binary_sensor
  condition:
  - condition: device
    device_id: 1d52216c126d3b76c4854515564d14d0
    domain: media_player
    entity_id: media_player.home_theater_appletv
    type: is_off
  action:
  - type: turn_on
    device_id: 2460edda7fbbeb7d702ba74eef896b34
    entity_id: light.home_theater_light
    domain: light
  mode: single
- id: '1664761495411'
  alias: Nightly Backup
  description: ''
  trigger:
  - platform: time
    at: 04:00:00
  condition: []
  action:
  - service: hassio.backup_partial
    data:
      homeassistant: true
  mode: single
- id: '1665000502764'
  alias: Batteries Warning
  description: ''
  use_blueprint:
    path: Low Battery Warning.yaml
    input:
      actions:
      - service: media_player.play_media
        target:
          entity_id: media_player.house_audio
        data:
          media_content_id: media-source://tts/google_translate?message=Battery+is+low+on+%7B%7B+sensors+%7D%7D+-+Tell+Jamie
          media_content_type: provider
        metadata:
          title: Battery is low on {{ sensors }} - Tell Jamie
          thumbnail: https://brands.home-assistant.io/_/google_translate/logo.png
          media_class: app
          children_media_class:
          navigateIds:
          - {}
          - media_content_type: app
            media_content_id: media-source://tts
          - media_content_type: provider
            media_content_id: media-source://tts/google_translate?message=Battery+is+low+on+%7B%7B+sensors+%7D%7D+-+Tell+Jamie
      time: '15:13:00'
