- id: '1665445926808'
  alias: To floor hallway light
  description: ''
  trigger:
  - type: occupied
    platform: device
    device_id: 7a271694c8a02d61384c08d571988a7a
    entity_id: binary_sensor.top_floor_hallway_nest_protect_occupancy
    domain: binary_sensor
  condition: []
  action:
  - type: turn_on
    device_id: c71e3da242134dd4b22c322b08f3cf17
    entity_id: light.top_floor_hallway
    domain: light
  mode: single
- id: '1671723988189'
  alias: Front Door Scene
  description: Toggle holiday lights
  use_blueprint:
    path: fxlt/zen32-scene-controller-z-wave-js.yaml
    input:
      zooz_switch: 0ca9601b44374b3932e2e4d9f5627689
      scene_1:
      - service: light.turn_on
        data:
          rgb_color:
          - 85
          - 153
          - 56
        target:
          entity_id: light.holiday_lights
      scene_2:
      - service: light.turn_off
        data: {}
        target:
          entity_id: light.holiday_lights
