# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  packages: !include_dir_named packages
  unit_system: imperial
  time_zone: America/Chicago
  country: US
recorder:
  db_url: mysql://homeassistant:hayo31@core-mariadb/homeassistant?charset=utf8mb4

# Text to speech
tts:
  - platform: google_translate

automation manual: !include_dir_merge_list automation
automation ui: !include automations.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
light: !include light_groups.yaml
alert: !include_dir_named alerts/

notify: !include notifications.yaml
input_boolean: !include_dir_merge_named input_boolean

influxdb: !include influxdb.yaml

# enable python scripts (in python_scripts folder)
python_script:

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret
  # "Project ID" in the Device Access Console (not Cloud Project ID!)
  project_id: 5782062e-da43-4cbe-bdb5-0e45bc0df826

frontend:
  themes: !include_dir_merge_named themes

lovelace:
  mode: storage
  # Add yaml dashboards
  dashboards:
    control-yaml:
      mode: yaml
      title: Control
      icon: mdi:script
      show_in_sidebar: true
      filename: ui/dashboard/control_center.yaml
  

# sensor:
#   - platform: google_keep
#     username: !secret google_username
#     password: !secret google_password
#     labels:
#       - 'Home Assistant'
#     pinned: true