# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  packages: !include_dir_named packages
  unit_system: imperial
  time_zone: America/Chicago

recorder:
  db_url: mysql://homeassistant:hayo31@core-mariadb/homeassistant?charset=utf8mb4
# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include_dir_merge_list automation
script: !include scripts.yaml
scene: !include scenes.yaml
light: !include light_groups.yaml

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret
  # "Project ID" in the Device Access Console (not Cloud Project ID!)
  project_id: 5782062e-da43-4cbe-bdb5-0e45bc0df826

sensor: !include sensors.yaml

frontend:
  themes: !include_dir_merge_named themes

lovelace:
  mode: storage
  # Add yaml dashboards
  dashboards:
    control-yaml:
      mode: yaml
      title: Control
      icon: mdi:script
      show_in_sidebar: true
      filename: ui/dashboard/control_center.yaml
    lovelace-yaml:
      mode: yaml
      title: Landing
      icon: mdi:script
      show_in_sidebar: true
      filename: ui/dashboard/landing.yaml