request_api:
  description: Request Petkit API
  target:
    entity:
      integration: petkit
      domain: sensor
  fields:
    api:
      description: Petkit API path
      example: /discovery/device_roster
      required: true
      selector:
        text:
    params:
      description: Request params
      example: '{"key":"val"}'
      selector:
        object:
    method:
      description: Request method
      default: GET
      example: GET
      selector:
        select:
          options:
            - GET
            - POST
            - POST_GET
    throw:
      description: Throw result
      default: true
      example: true
      selector:
        boolean: