- alias: Night Lights On
  trigger:
    - platform: sun
      event: sunset
      offset: "-00:30:00"
  condition: []
  action:
    - service: light.turn_on
      data: {}
      target:
        entity_id:
          - light.night_lights
          # - light.holiday_lights
  mode: single

- alias: Night Lights Off
  trigger:
    - platform: time
      at: "22:00:00"
  condition: []
  action:
    - service: light.turn_off
      data: {}
      target:
        entity_id:
          - light.exterior_lights
  mode: single
