sensor:
  - platform: history_stats
    name: "AAA-Test2 S22"
    entity_id: binary_sensor.s22_interactive
    state: "on"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"