# Used for Todoist card
# https://github.com/grinstantin/todoist-card

sensor:
  - platform: rest
    name: To-do List
    method: GET
    resource: "https://api.todoist.com/sync/v9/projects/get_data"
    params:
      project_id: 2296895971
    headers:
        Authorization: !secret todoist_api_token
    value_template: "{{ value_json['project']['id'] }}"
    json_attributes:
      - project
      - items
    scan_interval: 30

rest_command:
  todoist:
    method: post
    url: "https://api.todoist.com/sync/v9/{{ url }}"
    payload: '{{ payload }}'
    headers:
      Authorization: !secret todoist_api_token
    content_type: "application/x-www-form-urlencoded"
